
print("=" * 72)
print("S0 - SQOOP INGESTION RESULT")
print("=" * 72)
print(f"Laboratory environment                : S0")
print(f"Experiment ID                         : {EXPERIMENT_ID}")
print(f"Strategy under test                   : S0")
print(f"Dataset scale                         : {DATASET_SCALE}")
print(f"Source table                          : {SOURCE_TABLE}")
print(f"Expected records                      : {EXPECTED_RECORDS}")
print(f"Run number                            : {RUN_NUMBER}")
start_label = datetime.now().astimezone().isoformat(timespec="seconds")
print(f"Workflow start time                   : {start_label}")

thread = threading.Thread(target=monitor, daemon=True)
thread.start()
start = time.perf_counter()
result = subprocess.run(command)
elapsed = time.perf_counter() - start
stop_event.set()
thread.join()
end_label = datetime.now().astimezone().isoformat(timespec="seconds")

success = result.returncode == 0
size_mb = hdfs_size() if success else 0.0
status = "SUCCESS" if success else "FAILED"
print(f"Workflow end time                     : {end_label}")
print(f"Execution status                      : {status}")
print(f"Sqoop ingestion time                  : {elapsed:.2f} seconds")
print(f"Additional security-processing time   : 0.00 seconds")
print(f"HDFS output verified                  : {'PASS' if success and size_mb > 0 else 'FAIL'}")
print(f"Average CPU utilization               : {average(cpu_samples):.2f}%")
print(f"Peak CPU utilization                  : {max(cpu_samples) if cpu_samples else 0.0:.2f}%")
print(f"Average memory utilization            : {average(memory_samples):.2f}%")
print(f"Peak memory utilization               : {max(memory_samples) if memory_samples else 0.0:.2f}%")
print(f"HDFS storage size                     : {size_mb:.4f} MB")
print("Retry required                        : NO")
print("Number of retries                     : 0")
print(f"Error / failure message               : {'N/A' if success else 'Sqoop ingestion failed'}")
print(f"Abnormal condition observed           : {'NO' if success else 'YES'}")
print("S0 security indicators 1–3            : PASS (baseline controls)")
print("S1/S2/S3 indicators                   : N/A - not tested")
sys.exit(result.returncode)
